import { Country, Plan, PhysicalESIM } from './types';

export const countries: Country[] = [
  { code: 'US', name: 'United States', flag: '🇺🇸', region: 'North America' },
  { code: 'GB', name: 'United Kingdom', flag: '🇬🇧', region: 'Europe' },
  { code: 'FR', name: 'France', flag: '🇫🇷', region: 'Europe' },
  { code: 'ES', name: 'Spain', flag: '🇪🇸', region: 'Europe' },
  { code: 'IT', name: 'Italy', flag: '🇮🇹', region: 'Europe' },
  { code: 'DE', name: 'Germany', flag: '🇩🇪', region: 'Europe' },
  { code: 'JP', name: 'Japan', flag: '🇯🇵', region: 'Asia' },
  { code: 'AU', name: 'Australia', flag: '🇦🇺', region: 'Oceania' },
  { code: 'CA', name: 'Canada', flag: '🇨🇦', region: 'North America' },
  { code: 'BR', name: 'Brazil', flag: '🇧🇷', region: 'South America' },
  { code: 'MX', name: 'Mexico', flag: '🇲🇽', region: 'North America' },
  { code: 'TH', name: 'Thailand', flag: '🇹🇭', region: 'Asia' },
];

export const plans: Plan[] = [
  {
    id: 'us-1gb',
    countryCode: 'US',
    name: '1GB - 7 Days',
    data: '1GB',
    validity: '7 Days',
    price: 4.99,
    type: 'api',
    coverage: ['United States'],
    speed: '4G/5G',
    features: ['Instant activation', 'No contracts', 'Unlimited top-up'],
  },
  {
    id: 'us-3gb',
    countryCode: 'US',
    name: '3GB - 30 Days',
    data: '3GB',
    validity: '30 Days',
    price: 12.99,
    type: 'physical',
    coverage: ['United States'],
    speed: '4G/5G',
    features: ['Physical QR code', 'Premium support', 'Tethering allowed'],
  },
  {
    id: 'eu-5gb',
    countryCode: 'GB',
    name: 'Europe 5GB - 30 Days',
    data: '5GB',
    validity: '30 Days',
    price: 19.99,
    type: 'api',
    coverage: ['UK', 'France', 'Germany', 'Spain', 'Italy', '30+ countries'],
    speed: '4G/5G',
    features: ['Multi-country', 'Instant activation', 'Unlimited top-up'],
  },
  {
    id: 'jp-2gb',
    countryCode: 'JP',
    name: '2GB - 14 Days',
    data: '2GB',
    validity: '14 Days',
    price: 9.99,
    type: 'api',
    coverage: ['Japan'],
    speed: '4G/5G',
    features: ['Fast speeds', 'No throttling', '24/7 support'],
  },
  {
    id: 'global-10gb',
    countryCode: 'US',
    name: 'Global 10GB - 30 Days',
    data: '10GB',
    validity: '30 Days',
    price: 39.99,
    type: 'api',
    coverage: ['200+ countries worldwide'],
    speed: '4G/5G',
    features: ['Global coverage', 'Premium speeds', 'Priority support'],
  },
];

// In-memory database for physical eSIMs (in production, use a real database)
export const physicalESIMs: PhysicalESIM[] = [
  {
    id: 'esim-1',
    countryCode: 'US',
    planId: 'us-3gb',
    qrCode: 'LPA:1$esim.example.com$ACTIVATION-CODE-12345',
    qrCodeType: 'text',
    status: 'available',
  },
  {
    id: 'esim-2',
    countryCode: 'US',
    planId: 'us-3gb',
    qrCode: 'LPA:1$esim.example.com$ACTIVATION-CODE-67890',
    qrCodeType: 'text',
    status: 'available',
  },
];
