import { Shield, Lock, Eye, FileText, Scale, Globe, UserCheck, Bell, Server } from "lucide-react";

export default function PrivacyPolicyPage() {
  return (
    <div className="bg-white min-h-screen pb-20">
      
      {/* --- HERO SECTION --- */}
      <div className="bg-slate-900 text-white py-16 relative overflow-hidden">
        {/* Decoración de fondo estilo Quantum */}
        <div className="absolute top-0 right-0 w-96 h-96 bg-orange-500 rounded-full blur-[100px] opacity-20 -mr-20 -mt-20 pointer-events-none"></div>
        <div className="absolute bottom-0 left-0 w-72 h-72 bg-blue-600 rounded-full blur-[100px] opacity-10 -ml-20 -mb-20 pointer-events-none"></div>

        <div className="container mx-auto px-4 max-w-4xl relative z-10 text-center">
          <h1 className="text-3xl md:text-5xl font-extrabold mb-4">Privacy Policy</h1>
          <p className="text-slate-300 text-lg">
            At eSIM Quantum, transparency is part of our DNA.
          </p>
          <p className="text-sm text-slate-500 mt-4">Last updated: {new Date().getFullYear()}</p>
        </div>
      </div>

      {/* --- CONTENT --- */}
      <div className="container mx-auto px-4 max-w-4xl py-12">
        <div className="prose prose-lg max-w-none text-gray-600 space-y-12">
          
          <div className="bg-orange-50 p-6 rounded-2xl border border-orange-100">
            <p className="font-medium text-gray-800">
              We know that for you, your privacy is a fundamental right. That is why we want to explain our privacy policy clearly, so you have control and understand how we manage your personal data as a user of <strong>eSIM Quantum</strong> services.
            </p>
          </div>

          {/* 1. Principles */}
          <section>
            <h2 className="flex items-center gap-3 text-2xl font-bold text-gray-900 mb-6">
              <Scale className="text-orange-600 h-6 w-6" />
              1. Our Privacy Principles
            </h2>
            <p className="mb-4">These are the key principles that guide our commitment to your privacy:</p>
            <ul className="space-y-3 list-disc pl-5">
              <li><strong>Transparency:</strong> We will always keep you informed about how we use your data. No hidden fine print.</li>
              <li><strong>Purpose Limitation:</strong> We will only use your data for the specific purposes authorized (providing connectivity).</li>
              <li><strong>Data Minimization:</strong> We collect only the data strictly necessary to deliver your eSIM.</li>
              <li><strong>Security:</strong> We implement rigorous security measures to keep your data safe from unauthorized access.</li>
              <li><strong>Retention:</strong> We will not keep your data longer than necessary to provide the service or comply with laws.</li>
            </ul>
          </section>

          {/* 2. Data We Process */}
          <section>
            <h2 className="flex items-center gap-3 text-2xl font-bold text-gray-900 mb-6">
              <Eye className="text-orange-600 h-6 w-6" />
              2. What Data We Process
            </h2>
            <p className="mb-4">At eSIM Quantum, we process the data you provide to us and the data generated by the use of our services.</p>
            
            <h3 className="text-xl font-bold text-gray-800 mt-6 mb-3">2.1 Data provided by you</h3>
            <ul className="space-y-2 list-disc pl-5 mb-4">
              <li><strong>Contact Information:</strong> Name and email address. We need this to send you the QR code for your eSIM.</li>
              <li><strong>Payment Information:</strong> We do not store your full card details. Payments are processed via secure, certified third-party payment gateways.</li>
              <li><strong>Support Data:</strong> Information you provide when contacting our help desk to resolve technical issues.</li>
            </ul>

            <h3 className="text-xl font-bold text-gray-800 mt-6 mb-3">2.2 Data generated by usage</h3>
            <ul className="space-y-2 list-disc pl-5">
              <li><strong>Technical Identifiers:</strong> We process the ICCID (the unique serial number of your eSIM) to manage your plan.</li>
              <li><strong>Consumption Data:</strong> We monitor data volume usage (e.g., "2GB used out of 5GB") to show you your balance and prevent service interruption.</li>
              <li><strong>Device Info:</strong> We may detect your device model to ensure eSIM compatibility before purchase.</li>
            </ul>
          </section>

          {/* 3. Purpose */}
          <section>
            <h2 className="flex items-center gap-3 text-2xl font-bold text-gray-900 mb-6">
              <FileText className="text-orange-600 h-6 w-6" />
              3. Why We Process Your Data
            </h2>
            <p className="mb-4">We process your data to provide you with the best possible service:</p>
            <ul className="space-y-3 list-disc pl-5">
              <li><strong>Service Delivery:</strong> To generate, provision, and deliver your eSIM profile and ensure it connects to the network.</li>
              <li><strong>Customer Support:</strong> To identify your line and troubleshoot connectivity issues in destination countries.</li>
              <li><strong>Communications:</strong> To send you important transactional emails, such as your QR code, payment receipts, or low-data alerts.</li>
              <li><strong>Fraud Prevention:</strong> To detect and prevent abusive or fraudulent use of our payment systems.</li>
            </ul>
          </section>

          {/* 4. Sharing */}
          <section>
            <h2 className="flex items-center gap-3 text-2xl font-bold text-gray-900 mb-6">
              <Globe className="text-orange-600 h-6 w-6" />
              4. Information We Share
            </h2>
            <p className="mb-4">
              eSIM Quantum collaborates with trusted third parties to provide the service. We do not sell your data to advertisers. We share data only with:
            </p>
            <ul className="space-y-2 list-disc pl-5">
              <li><strong>Connectivity Providers:</strong> To activate your service, we must communicate technical identifiers (like ICCID) to global network aggregators.</li>
              <li><strong>Payment Processors:</strong> To execute transactions securely.</li>
              <li><strong>Legal Authorities:</strong> If required by law, we may share information with competent authorities (e.g., to comply with telecommunications regulations).</li>
            </ul>
          </section>

          {/* 5. Security & Retention */}
          <section>
            <h2 className="flex items-center gap-3 text-2xl font-bold text-gray-900 mb-6">
              <Lock className="text-orange-600 h-6 w-6" />
              5. Security and Retention
            </h2>
            
            <h3 className="text-xl font-bold text-gray-800 mt-4 mb-2">Security</h3>
            <p className="mb-4">
              We protect your data with rigorous security measures, including SSL encryption for all data in transit. We adopt technical means to prevent loss, misuse, or unauthorized access.
            </p>

            <h3 className="text-xl font-bold text-gray-800 mt-4 mb-2">Retention</h3>
            <p className="mb-4">
              We keep your data only as long as necessary.
            </p>
            <ul className="space-y-2 list-disc pl-5">
              <li><strong>Active Plans:</strong> While your eSIM is active.</li>
              <li><strong>Inactive Plans:</strong> We may retain purchase history for a limited period to comply with tax and legal obligations, after which it is anonymized or deleted.</li>
            </ul>
          </section>

          {/* 6. Your Rights */}
          <section>
            <h2 className="flex items-center gap-3 text-2xl font-bold text-gray-900 mb-6">
              <Shield className="text-orange-600 h-6 w-6" />
              6. Your Rights
            </h2>
            <p className="mb-4">As a user, you have full control over your data. You have the right to:</p>
            <div className="grid md:grid-cols-2 gap-4 mb-6">
              <div className="bg-gray-50 p-4 rounded-lg border border-gray-100"><strong>Access:</strong> Know what data we have about you.</div>
              <div className="bg-gray-50 p-4 rounded-lg border border-gray-100"><strong>Rectification:</strong> Correct errors in your info.</div>
              <div className="bg-gray-50 p-4 rounded-lg border border-gray-100"><strong>Deletion:</strong> Request that we delete your data ("Right to be forgotten").</div>
              <div className="bg-gray-50 p-4 rounded-lg border border-gray-100"><strong>Opposition:</strong> Object to specific processing.</div>
            </div>
            <p>
              To exercise any of these rights, simply contact our support team at: <a href="mailto:LR@esimquantum.com" className="text-orange-600 font-bold hover:underline">LR@esimquantum.com</a>
            </p>
          </section>

          {/* 7. Updates */}
          <section>
            <h2 className="flex items-center gap-3 text-2xl font-bold text-gray-900 mb-6">
              <Bell className="text-orange-600 h-6 w-6" />
              7. Updates to this Policy
            </h2>
            <p>
              This Privacy Policy may evolve. If we make significant changes that affect your rights, we will inform you via email or a prominent notice on our website. Continued use of eSIM Quantum services implies acceptance of the updated terms.
            </p>
          </section>

        </div>
      </div>
    </div>
  );
}
